### PR TITLE
Enhance javlibrary scraper

### PR DESCRIPTION
**Pull request by ScrappingFTW**
JavLibrary scraper has been slow because of two things: the crappy search page and cross-linking the actor list from DMM.

The search page returns tons of results, for ids like XXX-001 you also get XXX-010, XXX-011 and so on. Then the movie selection dialog ends downloading up to 20 thumbnails just to select the first (correct) one. I fixed this by manually filtering results that don't match the original file movie id.

Scraping the DMM page to get the missing actor thumbnails is quite a nice feature. It should be moved to an upper level class, so other scrapers can benefit for it too. It's also quite slow at the moment so I removed it until I figure out a way to do that. Of course you can revert this commit if you want it back.

Finally, I'm scrapping the japanese page to get the original title. It's still quite fast so it's probably a good idea, for sites that support it, to download both languages and keep both documents within the scraper. This could also be used to find the japanese actor names and search the images on DMM.

I'm also looking for a faster way to translate DMM content, maybe scraping a full, google translated page, or submitting all the scraped text on a single request.

### CODE REVIEW

**Comment by DoctorD1501** [comment]
I'm probably going to try to integrate the actor image amalgamation further up like you suggested as part of my overhaul of the amalgamation system I'm currently working on. That way the program won't double or triple scraping the same site just to get actor images, which I think is what you're trying to do here to speed things up a bit.

However, in the mean time, if we use JavLibrary as our preferred actor source, it would be nice to still get the images. Can you revert the change to remove the cross linking of DMM? Then I'll merge this pull request in.

Thanks.

**Comment by ScrappingFTW** [comment]
OK, I reverted it.

I also found a different way to get the actor thumbnails and translated names from DMM. You can get it from here:
https://gist.github.com/ScrappingFTW/0d8d3b82bc425f234315

**Comment by DoctorD1501** [comment]
Besides being a whole lot shorter, what's the main advantage of this new way of getting actor names in DMM? When I looked through existing code from Dmm's scrapeActor() I see a TON of special casing and extra stuff I wrote a long time ago that seems to be doing ...something... (hey...it's been a while since I wrote this!) because DMM's current results are generally pretty good I think.

**Comment by ScrappingFTW** [comment]
If you are translating japanese content, you get good actor names for free, way better than using thumbnail's file name or google translate. 

I was not trying to replace DMM scraping really, I was looking for a faster way to cross-link actor thumbnails. Translated actor names came as a nice bonus. Unfortunately, the search only works for japanese names, no luck for english sites so far.

**Comment by DoctorD1501** [comment]
Cool. Well, feel free to throw it in a commit or branch and I'll try it out!

**Pull request merged**
