### PR TITLE
Maven

### PR DESCRIPTION
**Pull request by reapier**
Using Maven, refactored some code.

### CODE REVIEW

**Comment by DarkMask100** [comment]
From the looks of it, I'd say this project is abandoned. Considering the current version is pretty much broken, I'm sure users would love to see this project continue on and it seems you have the skill for it.

**Comment by Still34** [comment]
The savior we need; this version even has CI.

**Comment by Wizell** [comment]
I tried this pull request and the AmalgamationSettings.json un/serialization is broken.

**Comment by Wizell** [comment]
Many improvement of the pull request was integrated in the replacement of ants by gradle instead of maven.

Thank you for the proposition

**Pull request closed without merging**
